/**
 * Build-time codegen script that reads Lucide SVG files from the lucide-static
 * npm package and produces a TypeScript module with a Map<string, string>.
 *
 * Usage: bun scripts/generate-icon-data.ts
 * Output: src/claude_figma_mcp/data/lucide-icons.ts
 */

import { readdir, readFile, mkdir, writeFile } from "node:fs/promises";
import { join, basename } from "node:path";

const ICONS_DIR = join(import.meta.dir, "..", "node_modules", "lucide-static", "icons");
const OUTPUT_DIR = join(import.meta.dir, "..", "src", "claude_figma_mcp", "data");
const OUTPUT_FILE = join(OUTPUT_DIR, "lucide-icons.ts");

async function main() {
  const files = (await readdir(ICONS_DIR)).filter((f) => f.endsWith(".svg")).sort();

  console.log(`Found ${files.length} SVG files in lucide-static`);

  const entries: string[] = [];

  for (const file of files) {
    const name = basename(file, ".svg");
    const svg = (await readFile(join(ICONS_DIR, file), "utf-8")).trim();
    // Escape backticks and backslashes for template literal safety
    const escaped = svg.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$/g, "\\$");
    entries.push(`  ["${name}", \`${escaped}\`]`);
  }

  const output = `// Auto-generated by scripts/generate-icon-data.ts — DO NOT EDIT
// ${files.length} Lucide icons (from lucide-static npm package)

export const LUCIDE_ICONS: Map<string, string> = new Map([
${entries.join(",\n")}
]);

export const LUCIDE_ICON_NAMES: string[] = [...LUCIDE_ICONS.keys()].sort();
`;

  await mkdir(OUTPUT_DIR, { recursive: true });
  await writeFile(OUTPUT_FILE, output, "utf-8");

  console.log(`Generated ${OUTPUT_FILE} with ${files.length} entries`);
}

main().catch((err) => {
  console.error("Error generating icon data:", err);
  process.exit(1);
});
